import { PrismaClient } from "@prisma/client"
import { hash } from "bcryptjs"

const prisma = new PrismaClient()

// Dados de exemplo de imóveis com status variados
const sampleDeals = [
  {
    propertyName: "Apartamento Jardins - SP",
    propertyType: "Apartamento",
    address: "Rua Oscar Freire, 1200 - Jardins, São Paulo/SP",
    status: "Alugado", // Holding - gerando renda passiva
    purchasePrice: 850000,
    acquisitionCosts: 42500,
    monthlyRent: 4500, // Renda mensal de aluguel
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 30,
    auctioneerFeePercent: null,
    itbiPercent: 3,
    registryCost: 4500,
    financingEnabled: true,
    interestRateAnnual: 11.5,
    termMonths: 360,
    amortizationType: "SAC",
    iptuDebt: 0,
    condoDebt: 0,
    resalePrice: 1100000,
    resaleDiscountPercent: 5,
    brokerFeePercent: 6,
    monthlyCondoFee: 1200,
    monthlyIptu: 450,
    expectedSaleMonths: 18,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.22,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
  {
    propertyName: "Casa em Leilão - Alphaville",
    propertyType: "Casa",
    address: "Alameda Grajaú, 450 - Alphaville, Barueri/SP",
    status: "Em reforma", // Recém comprado, em obras
    purchasePrice: 1200000,
    acquisitionCosts: 96000,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 40,
    auctioneerFeePercent: 5,
    itbiPercent: 3,
    registryCost: 6000,
    financingEnabled: true,
    interestRateAnnual: 12,
    termMonths: 300,
    amortizationType: "PRICE",
    iptuDebt: 15000,
    condoDebt: 8000,
    resalePrice: 1800000,
    resaleDiscountPercent: 10,
    brokerFeePercent: 6,
    monthlyCondoFee: 1800,
    monthlyIptu: 800,
    expectedSaleMonths: 24,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.35,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: true,
  },
  {
    propertyName: "Kitnet Centro - RJ",
    propertyType: "Apartamento",
    address: "Rua do Ouvidor, 80 - Centro, Rio de Janeiro/RJ",
    status: "Vendido", // Deal finalizado
    purchasePrice: 180000,
    acquisitionCosts: 9000,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 50,
    auctioneerFeePercent: null,
    itbiPercent: 2,
    registryCost: 2500,
    financingEnabled: true,
    interestRateAnnual: 10.5,
    termMonths: 240,
    amortizationType: "SAC",
    iptuDebt: 0,
    condoDebt: 2500,
    resalePrice: 250000,
    resaleDiscountPercent: 0,
    brokerFeePercent: 6,
    monthlyCondoFee: 450,
    monthlyIptu: 120,
    expectedSaleMonths: 12,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.28,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
  {
    propertyName: "Sobrado Leilão Judicial - Curitiba",
    propertyType: "Casa",
    address: "Rua XV de Novembro, 1500 - Centro, Curitiba/PR",
    status: "Aprovado", // Viabilidade aprovada, negociando
    purchasePrice: 420000,
    acquisitionCosts: 33600,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 25,
    auctioneerFeePercent: 5,
    itbiPercent: 3,
    registryCost: 3500,
    financingEnabled: true,
    interestRateAnnual: 11,
    termMonths: 360,
    amortizationType: "SAC",
    iptuDebt: 25000,
    condoDebt: 0,
    resalePrice: 650000,
    resaleDiscountPercent: 8,
    brokerFeePercent: 6,
    monthlyCondoFee: 0,
    monthlyIptu: 350,
    expectedSaleMonths: 18,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.31,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: true,
  },
  {
    propertyName: "Cobertura Barra - RJ",
    propertyType: "Apartamento",
    address: "Av. Lúcio Costa, 3200 - Barra da Tijuca, Rio de Janeiro/RJ",
    status: "À venda", // Anunciado no mercado
    purchasePrice: 2500000,
    acquisitionCosts: 125000,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 35,
    auctioneerFeePercent: null,
    itbiPercent: 3,
    registryCost: 12000,
    financingEnabled: true,
    interestRateAnnual: 10,
    termMonths: 360,
    amortizationType: "PRICE",
    iptuDebt: 0,
    condoDebt: 0,
    resalePrice: 3200000,
    resaleDiscountPercent: 5,
    brokerFeePercent: 5,
    monthlyCondoFee: 3500,
    monthlyIptu: 1200,
    expectedSaleMonths: 24,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.18,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: true,
    riskHighLeverage: false,
  },
  {
    propertyName: "Apartamento Leilão - BH",
    propertyType: "Apartamento",
    address: "Av. Afonso Pena, 2800 - Funcionários, Belo Horizonte/MG",
    status: "Comprado", // Imóvel adquirido
    purchasePrice: 380000,
    acquisitionCosts: 30400,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 30,
    auctioneerFeePercent: 5,
    itbiPercent: 3,
    registryCost: 3000,
    financingEnabled: true,
    interestRateAnnual: 11.5,
    termMonths: 300,
    amortizationType: "SAC",
    iptuDebt: 8000,
    condoDebt: 12000,
    resalePrice: 550000,
    resaleDiscountPercent: 5,
    brokerFeePercent: 6,
    monthlyCondoFee: 800,
    monthlyIptu: 280,
    expectedSaleMonths: 15,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.29,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
  {
    propertyName: "Studio Pinheiros - SP",
    propertyType: "Apartamento",
    address: "Rua dos Pinheiros, 900 - Pinheiros, São Paulo/SP",
    status: "Alugado", // Holding - gerando renda passiva
    purchasePrice: 320000,
    acquisitionCosts: 16000,
    monthlyRent: 2200, // Renda mensal de aluguel
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 100,
    auctioneerFeePercent: null,
    itbiPercent: 3,
    registryCost: 2800,
    financingEnabled: false,
    interestRateAnnual: null,
    termMonths: null,
    amortizationType: null,
    iptuDebt: 0,
    condoDebt: 0,
    resalePrice: 420000,
    resaleDiscountPercent: 0,
    brokerFeePercent: 6,
    monthlyCondoFee: 650,
    monthlyIptu: 180,
    expectedSaleMonths: 10,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.25,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
  {
    propertyName: "Terreno Leilão - Campinas",
    propertyType: "Lote",
    address: "Rod. D. Pedro I, km 132 - Campinas/SP",
    status: "Arquivado", // Descartado
    purchasePrice: 150000,
    acquisitionCosts: 12000,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 100,
    auctioneerFeePercent: 5,
    itbiPercent: 3,
    registryCost: 2000,
    financingEnabled: false,
    interestRateAnnual: null,
    termMonths: null,
    amortizationType: null,
    iptuDebt: 5000,
    condoDebt: 0,
    resalePrice: 280000,
    resaleDiscountPercent: 10,
    brokerFeePercent: 6,
    monthlyCondoFee: 0,
    monthlyIptu: 80,
    expectedSaleMonths: 36,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.45,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
  {
    propertyName: "Flat Itaim - SP",
    propertyType: "Apartamento",
    address: "Rua João Cachoeira, 350 - Itaim Bibi, São Paulo/SP",
    status: "Em análise", // Em pipeline
    purchasePrice: 480000,
    acquisitionCosts: 24000,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 40,
    auctioneerFeePercent: null,
    itbiPercent: 3,
    registryCost: 3500,
    financingEnabled: true,
    interestRateAnnual: 10.5,
    termMonths: 240,
    amortizationType: "PRICE",
    iptuDebt: 0,
    condoDebt: 0,
    resalePrice: 620000,
    resaleDiscountPercent: 5,
    brokerFeePercent: 6,
    monthlyCondoFee: 1100,
    monthlyIptu: 320,
    expectedSaleMonths: 14,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.21,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
  {
    propertyName: "Casa Leilão Extrajudicial - Floripa",
    propertyType: "Casa",
    address: "Rua das Rendeiras, 800 - Lagoa da Conceição, Florianópolis/SC",
    status: "Em análise", // Em pipeline
    purchasePrice: 750000,
    acquisitionCosts: 60000,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 35,
    auctioneerFeePercent: 5,
    itbiPercent: 3,
    registryCost: 5000,
    financingEnabled: true,
    interestRateAnnual: 11,
    termMonths: 360,
    amortizationType: "SAC",
    iptuDebt: 12000,
    condoDebt: 0,
    resalePrice: 1150000,
    resaleDiscountPercent: 8,
    brokerFeePercent: 6,
    monthlyCondoFee: 0,
    monthlyIptu: 450,
    expectedSaleMonths: 20,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.33,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: true,
  },
  {
    propertyName: "Apartamento Vila Madalena - SP",
    propertyType: "Apartamento",
    address: "Rua Harmonia, 250 - Vila Madalena, São Paulo/SP",
    status: "Alugado", // Holding - gerando renda passiva
    purchasePrice: 620000,
    acquisitionCosts: 31000,
    monthlyRent: 3200, // Renda mensal de aluguel
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 25,
    auctioneerFeePercent: null,
    itbiPercent: 3,
    registryCost: 4000,
    financingEnabled: true,
    interestRateAnnual: 11.5,
    termMonths: 360,
    amortizationType: "SAC",
    iptuDebt: 0,
    condoDebt: 3500,
    resalePrice: 820000,
    resaleDiscountPercent: 5,
    brokerFeePercent: 6,
    monthlyCondoFee: 900,
    monthlyIptu: 350,
    expectedSaleMonths: 16,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.24,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: true,
  },
  {
    propertyName: "Sala Comercial - Paulista",
    propertyType: "Comercial",
    address: "Av. Paulista, 1800 - Bela Vista, São Paulo/SP",
    status: "Em análise", // Em pipeline
    purchasePrice: 950000,
    acquisitionCosts: 47500,
    monthlyRent: 0,
    monthlyExpenses: 0,
    annualPropertyTax: 0,
    downPaymentPercent: 50,
    auctioneerFeePercent: null,
    itbiPercent: 3,
    registryCost: 5500,
    financingEnabled: true,
    interestRateAnnual: 12,
    termMonths: 240,
    amortizationType: "PRICE",
    iptuDebt: 0,
    condoDebt: 0,
    resalePrice: 1250000,
    resaleDiscountPercent: 5,
    brokerFeePercent: 5,
    monthlyCondoFee: 1800,
    monthlyIptu: 650,
    expectedSaleMonths: 18,
    monthlyCashFlow: 0,
    annualCashFlow: 0,
    roi: 0.22,
    capRate: 0,
    paybackYears: 0,
    riskNegativeCashFlow: false,
    riskLowROI: false,
    riskHighLeverage: false,
  },
]

async function main() {
  console.log("🌱 Iniciando seed...")

  // Usuário de teste para desenvolvimento
  const testEmail = "maikon.sebastiani@gmail.com"
  const testPassword = "12345678"

  let user = await prisma.user.findUnique({
    where: { email: testEmail },
  })

  if (!user) {
    const hashedPassword = await hash(testPassword, 12)
    user = await prisma.user.create({
      data: {
        email: testEmail,
        password: hashedPassword,
        name: "Dev User",
      },
    })
    console.log(`✅ Usuário de teste criado: ${user.email}`)
  } else {
    console.log(`✅ Usuário de teste já existe: ${testEmail}`)
  }

  // Criar deals de exemplo
  console.log("📦 Criando deals de exemplo...")
  
  for (const dealData of sampleDeals) {
    await prisma.deal.create({
      data: {
        userId: user.id,
        ...dealData,
      },
    })
  }
  
  const totalDeals = await prisma.deal.count({
    where: { userId: user.id },
  })
  
  console.log(`✅ ${sampleDeals.length} novos deals criados!`)
  console.log(`📊 Total de deals do usuário: ${totalDeals}`)

  console.log("")
  console.log(`📧 Email: ${testEmail}`)
  console.log(`🔑 Senha: ${testPassword}`)
  console.log("")
  console.log("🌱 Seed concluído!")
}

main()
  .catch((e) => {
    console.error("❌ Erro no seed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
